<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['myconfig']	=	array(
								'assets'				=>	'assets',
								'bootstrap4css'			=>	'assets/bootstrap/4.0/css/bootstrap.css',
								'bootstrapcss'			=>	'assets/bootstrap/css/bootstrap.css',
								'bootstrap4js'			=>	'assets/bootstrap/4.0/js/bootstrap.js',
								'bootstrapjs'			=>	'assets/bootstrap/js/bootstrap.js',
								'bootstrap_chosencss'	=>	'assets/bootstrap-chosen-master/css/bootstrap-chosen.css',
								'bootstrap_chosenjs'	=>	'assets/bootstrap-chosen-master/js/chosen.jquery.js',
								'ckeditorjs'			=>	'assets/ckeditor_standard/ckeditor.js',
								'ckeditor5js'			=>	'assets/ckeditor5/ckeditor.js',
								'ckeditor5ptbrjs'		=>	'assets/ckeditor5/language/pt-br.js',
								'cpf_cnpjjs'			=>	'assets/js/cpf_cnpj.js',
								'datatablesbootstrapjs'	=>	'assets/datatables/media/js/dataTables.bootstrap.js',
								'datatablescss'			=>	'assets/datatables/media/css/dataTables.bootstrap.css',
								'datatablesjs'			=>	'assets/datatables/media/js/jquery.dataTables.js',
								'datetimemomentjs'		=>	'assets/datetimemoment/datetime-moment.js',
								'favicon'				=>	'assets/images/favicon.png',
								'fontawesomejs'			=>	'assets/fontawesome/5.1.0/js/all.js',
								'fontawesomecss'		=>	'assets/fontawesome/5.1.0/css/all.css',
								'functionsjs'			=>	'assets/js/functions.js',
								'holderjs'				=>	'assets/imsky-holder/holder.js',
								'images'				=>	'assets/images',
								'jqueryformjs'			=>	'assets/ajaxphpupload/jquery.form.min.js',
								'jqueryslimjs'			=>	'assets/jquery/jquery3.3.1.js',
								'jqueryjs'				=>	'assets/jquery/jquery2.1.3.js',
								'jasny_bootstrapjs'		=>	'assets/jasny_bootstrap/js/jasny_bootstrap.js',
								'jasny_bootstrapcss'	=>	'assets/jasny_bootstrap/css/jasny_bootstrap.css',
								'momentjs'				=>	'assets/moment/moment.js',
								'moment_localejs'		=>	'assets/moment/moment-with-locales.js',
								'popperjs'				=>	'assets/jquery/popper.js',
								'pagingjs'				=>	'assets/js/paging.js',
								'stylecss'				=>	'assets/css/styles.css',
								'scriptjs'				=>	'assets/js/script.js',
								'tinymcejs'				=>	'assets/tinymce_4.7.13/tinymce.min.js',
								'toastrcss'				=>	'assets/toastr/toastr.css',
								'toastrjs'				=>	'assets/toastr/toastr.js',
								'title'					=>	'.:: PHYSIS WEB ::.',
								'copyright'				=>	'2018 - PHYSIS WEB© - Brazil',
								'webshim'				=>	'assets/webshim/js-webshim/minified/polyfiller.js',
							);

$config['arquivos']	=	array(
								'backupDB'				=>	'assets/backupDB',
								'backupTB'				=>	'assets/backupTB',
								'licencas_docs'			=>	'assets/uploads/licencas_docs/',
								'docs_despachos'		=>	'assets/uploads/docs_despachos/',
								'assinatura_usuario'	=>	'assets/uploads/assinaturas_usuarios',
								'imagens_parecer'		=>	'assets/uploads/imagens_parecer',
							);